DEFAULT_DOWNLOAD_APP = '/usr/bin/transmission-cli'
DEFAULT_DOWNLOAD_APP_ARGS = ''
DEFAULT_DOWNLOAD_FOLDER = '/var/movies'
DEFAULT_UPLOAD_TIME = 30
DEFAULT_SCAN_FOLDER = '/var/movies'
DEFAULT_SCAN_INTERVAL = '30'

